"""baseline: schema in sync

Revision ID: 086094a6329e
Revises: 
Create Date: 2026-07-01 23:00:26.837737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '086094a6329e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
